### ISSUE TITLE
חסרות הוראות וחסר משוב

### ISSUE THREAD

**Issue by erelsgl** [project-happy/cosmo-type#1]
א. חסרות הוראות לשחקן בתחילת המשחק -מה בדיוק הוא צריך לעשות.

ב. חסר משוב: אני לוחץ על אות, ולא יודע איזה אות נקלטה (לדוגמה, בהתחלה המקלדת שלי היתה במצב עברית, ולכן כנראה כל ההקלדות שלי לא השפיעו). צריך שכששחקן לוחץ על אות מסוימת, האות הזאת תופיע על המסך, כדי שהשחקן יידע מה המחשב קלט.

ג. לי אישית המשחק היה איטי מדי - אולי כי אני רגיל להקליד מהר.

ד. המשחק יהיה הרבה יותר מעניין עם שני שחקנים.

**Comment by tarikz-h** [comment]
שלום אראל ,
אנחנו נעלה גרסה מעודכנת בהמשך היום
תודה
טארק , ויסאם

‫ב-12 ביוני 2023, בשעה 14:04, ‏‏Erel Segal-Halevi ***@***.***> כתב/ה:‬

﻿

א. חסרות הוראות לשחקן בתחילת המשחק -מה בדיוק הוא צריך לעשות.

ב. חסר משוב: אני לוחץ על אות, ולא יודע איזה אות נקלטה (לדוגמה, בהתחלה המקלדת שלי היתה במצב עברית, ולכן כנראה כל ההקלדות שלי לא השפיעו). צריך שכששחקן לוחץ על אות מסוימת, האות הזאת תופיע על המסך, כדי שהשחקן יידע שהמחשב קלט אותו. כדאי גם לעשות שהאות הזאת תהיה מודגשת בתוך המילה שעל החללית, כדי שהשחקן יבין שהוא מתקדם.

**Comment by erelsgl** [comment]
ג. לי אישית המשחק היה איטי מדי - אולי כי אני רגיל להקליד מהר. אולי כדאי להוסיף רמות קושי שונות.

ד. המשחק יהיה הרבה יותר מעניין עם שני שחקנים.

**Comment by tarikz-h** [comment]
מסכים שני משחקים יותר מעניין,
אנחנו נעלה עדכון כולל ,
Learning mode , normal mode , multi player
יש לנו קצת קושי עם הmultiplayer אבל מאמין שנתגבר על זה
נעדכן אותך


‫ב-12 ביוני 2023, בשעה 16:56, ‏‏Erel Segal-Halevi ***@***.***> כתב/ה:‬

﻿

ג. לי אישית המשחק היה איטי מדי - אולי כי אני רגיל להקליד מהר. אולי כדאי להוסיף רמות קושי שונות.

ד. המשחק יהיה הרבה יותר מעניין עם שני שחקנים.
