### ISSUE TITLE
הקלדה

### ISSUE THREAD

**Issue by VictoKu1** [project-happy/cosmo-type#2]
בשלב ה Tutorial ההקלדה לא עובדת.

**Comment by VictoKu1** [comment]
כדאי להוסיף משהו שמראה את הניקוד ואת הדיוק במהלך המשחק ולא רק כשנפסלים.

**Comment by VictoKu1** [comment]
במשחק רשת זה יכול לקחת הרבה זמן עד שזה נותן להתחבר.

**Comment by VictoKu1** [comment]
ב Tutorial אי אפשר לעצור את המשחק ולחזור לתפריט הראשי כמו במצבי משחק אחרים.

**Comment by VictoKu1** [comment]
ב Story mode אם מנסים לעצור את המשחק לפני שהוא מתחיל (לדוגמא כדי לחזור למסך הראשי) זה לא מאפשר ללחוץ על שום דבר, כנראה בגלל שזה מופיע ב Layer יותר נמוך משאר הדברים.

**Comment by Wissam111** [comment]
Updated version : https://wissam111.itch.io/cosmo-type.
The multiplayer mode will be fixed/updated soon.
